apiVersion: v2
name: ddb-proxy
description: A Helm chart for deploying ddb-proxy
type: application
version: 0.1.1
appVersion: "0.0.25"
keywords:
  - proxy
  - vtt
  - virtualtabletop
  - foundryvtt
  - foundry
  - ddb
  - muncher
sources:
  - https://github.com/TheNightAngel17/helm-charts/tree/main/charts/foundry-vtt
maintainers:
  - name: thenightangel17
    email: 29760146+TheNightAngel17@users.noreply.github.com