apiVersion: v2
name: mlx-portfolio
description: A Helm chart for deploying my portfolio website
type: application
version: 0.1.1
appVersion: "0.0.2"
keywords:
  - website
  - portfolio
  - personal
sources:
  - https://github.com/TheNightAngel17/helm-charts/tree/main/charts/mlx-portfolio
maintainers:
  - name: thenightangel17
    email: 29760146+TheNightAngel17@users.noreply.github.com
